import React from 'react';
import * as XLSX from 'xlsx';
import {
  UploadCloud, Sparkles, ArrowRight, CheckCircle, Zap, RefreshCw, AlertTriangle, Check, Download, FileSpreadsheet
} from 'lucide-react';
import { UCID, UCIDStep, Solution, Snapshot } from '../../types';
import { SolutionConfigCard } from './SolutionConfigCard';
import { SourcingReconciliationDiff } from './SourcingReconciliationDiff';

interface StepContentPanelProps {
  ucid: UCID;
  activeStep: UCIDStep;
  runningIntel: string | null;
  intelProgress: number;
  committingSnapshot: boolean;
  onRunIntel: () => void;
  onAdvance: () => void;
  onCommitSnapshot: () => void;
  appendLogEvent: (level: 'info' | 'warn' | 'ok' | 'err', msg: string) => void;
  onUpdateSolutions: (sols: Solution[]) => void;
  onUpdateBOM: (rawText: string) => void;
  onShowToast: (msg: string, type: 'success' | 'warn' | 'error') => void;
}

export function StepContentPanel({
  ucid,
  activeStep,
  runningIntel,
  intelProgress,
  committingSnapshot,
  onRunIntel,
  onAdvance,
  onCommitSnapshot,
  appendLogEvent,
  onUpdateSolutions,
  onUpdateBOM,
  onShowToast,
}: StepContentPanelProps) {

  const isRunning = runningIntel === uucidId(ucid);

  function uucidId(u: UCID) {
    return u.id;
  }

  switch (activeStep) {
    case 'boq-intake': {
      const handleSimulateIntake = async (fileName: string, presetType: 'hpe-legacy' | 'dell-overcharge' | 'cisco-asymmetry') => {
        let rawText = '';
        let sols: Solution[] = [];
        
        if (presetType === 'hpe-legacy') {
          rawText = `[AUTOMATED WORKBOOK INGESTION - HPE LOGGED QUOTE]\nFile: HPE_PARTNER_QUOTE_6130_EOL.xlsx\nTarget Chassis: DL380 Gen11 NC SFF (P40411-B21) x10 Units\nProcessed CPU SKU: 815100-B21 (Intel Xeon Gold 6130 Legacy CPU) x20 Units\nMemory DIMM RAM: P38454-B21 (64GB DDR5) x80 Units\n\nNotes: Lead duration set to 45 Days due to obsolete processor SKU.`;
          
          sols = [
            {
              id: `sol-manual-hpe-${Date.now()}`,
              vendor: 'HPE',
              label: 'HPE Alternative (Ingested: HPE_PARTNER_QUOTE_6130_EOL.xlsx)',
              totalPrice: 118200,
              originalPrice: 125000,
              savings: 6800,
              complianceScore: 78,
              items: [
                { id: 'item-mi-1', partNumber: 'P40411-B21', name: 'HPE ProLiant DL380 Gen11 CTO Chassis', type: 'Chassis', quantity: 10, unitPrice: 3400 },
                { id: 'item-mi-2', partNumber: '815100-B21', name: 'Intel Xeon Gold 6130 Processor [EOL Sourcing Risk]', type: 'Processor', quantity: 20, unitPrice: 1890 },
                { id: 'item-mi-3', partNumber: 'P38454-B21', name: 'HPE 64GB DDR5 memory module RDIMM', type: 'Memory', quantity: 80, unitPrice: 580 }
              ]
            },
            {
              id: `sol-manual-dell-${Date.now()}`,
              vendor: 'Dell',
              label: 'Dell Alternative (Autogenerated Peer Modern Equivalent)',
              totalPrice: 120100,
              originalPrice: 125200,
              savings: 5100,
              complianceScore: 98,
              items: [
                { id: 'item-mi-d1', partNumber: '210-BFXS', name: 'Dell PowerEdge R760 8SFF Chassis', type: 'Chassis', quantity: 10, unitPrice: 3250 },
                { id: 'item-mi-d2', partNumber: '338-CHYT', name: 'Intel Xeon Gold 6430 32-Core CPU', type: 'Processor', quantity: 20, unitPrice: 2190 },
                { id: 'item-mi-d3', partNumber: '370-AHFF', name: 'Dell 64GB RDIMM 4800MT/s RAM', type: 'Memory', quantity: 40, unitPrice: 595 }
              ]
            }
          ];
        } else if (presetType === 'dell-overcharge') {
          rawText = `[AUTOMATED WORKBOOK INGESTION - DELL PREMIER PORTAL]\nFile: DELL_PREMIER_QUOTE_DRAFT.csv\nTarget Chassis: Dell PowerEdge R760 8SFF (210-BFXS) x12 Units\nStorage Drive SKU: 400-BPSB (Dell 3.84TB SAS Read Intensive SSD SFF) x24 Units [Mark-up: quote price is $1,590 vs contract $1,190]\nMemory: 370-AHFF (64GB RDIMM DDR5) x48 Units`;
          
          sols = [
            {
              id: `sol-manual-dell-${Date.now()}`,
              vendor: 'Dell',
              label: 'Dell Alternative (Ingested: DELL_PREMIER_QUOTE_DRAFT.csv)',
              totalPrice: 105720,
              originalPrice: 115000,
              savings: 9280,
              complianceScore: 85,
              items: [
                { id: 'item-mi-de1', partNumber: '210-BFXS', name: 'Dell PowerEdge R760 8SFF Chassis Base Unit', type: 'Chassis', quantity: 12, unitPrice: 3250 },
                { id: 'item-mi-de2', partNumber: '400-BPSB', name: 'Dell 3.84TB SAS Read Intensive SSD SFF [Markup Variance]', type: 'Drive', quantity: 24, unitPrice: 1590 },
                { id: 'item-mi-de3', partNumber: '370-AHFF', name: 'Dell 64GB RDIMM 4800MT/s memory module', type: 'Memory', quantity: 48, unitPrice: 595 }
              ]
            },
            {
              id: `sol-manual-hpe-${Date.now()}`,
              vendor: 'HPE',
              label: 'HPE Alternative (Autogenerated Peer Base)',
              totalPrice: 98160,
              originalPrice: 110000,
              savings: 11840,
              complianceScore: 98,
              items: [
                { id: 'item-mi-h1', partNumber: 'P40411-B21', name: 'HPE ProLiant DL380 Gen11 8SFF Chassis', type: 'Chassis', quantity: 12, unitPrice: 3400 },
                { id: 'item-mi-h2', partNumber: 'P40483-B21', name: 'HPE 3.84TB NVMe SSD Sourced', type: 'Drive', quantity: 24, unitPrice: 1220 },
                { id: 'item-mi-h3', partNumber: 'P38454-B21', name: 'HPE 64GB Dual Rank DDR5 module', type: 'Memory', quantity: 48, unitPrice: 580 }
              ]
            }
          ];
        } else {
          rawText = `[AUTOMATED WORKBOOK INGESTION - CISCO MATRIX CHALLENGE]\nFile: CISCO_UCS_AS_SYMMETRICAL.csv\nTarget Chassis: UCS C240 M7 Rack Server (UCSC-C240-M7S) x12 Units\nProcessor Unit: UCS-CPU-I6430 x24 Units\nMemory Allocation: UCS-MR-64G2ED-E (Cisco 64GB DDR5 RDIMM) x5 modules/node [Total Qty: 60 units]`;
          
          sols = [
            {
              id: `sol-manual-cisco-${Date.now()}`,
              vendor: 'Cisco',
              label: 'Cisco Alternative (Ingested: CISCO_UCS_AS_SYMMETRICAL.csv)',
              totalPrice: 140520,
              originalPrice: 148000,
              savings: 7480,
              complianceScore: 82,
              items: [
                { id: 'item-mi-c1', partNumber: 'UCSC-C240-M7S', name: 'Cisco UCS C240 M7 Rack Server Chassis', type: 'Chassis', quantity: 12, unitPrice: 4100 },
                { id: 'item-mi-c2', partNumber: 'UCS-CPU-I6430', name: 'UCS Intel Xeon Gold 6430 32-Core CPU', type: 'Processor', quantity: 24, unitPrice: 2280 },
                { id: 'item-mi-c3', partNumber: 'UCS-MR-64G2ED-E', name: 'UCS 64GB DDR5 memory module [Asymmetric Layout]', type: 'Memory', quantity: 60, unitPrice: 610 }
              ]
            },
            {
              id: `sol-manual-dell-${Date.now()}`,
              vendor: 'Dell',
              label: 'Dell Alternative (Autogenerated Peer Base)',
              totalPrice: 138000,
              originalPrice: 145000,
              savings: 7000,
              complianceScore: 98,
              items: [
                { id: 'item-mi-cd1', partNumber: '210-BFXS', name: 'Dell PowerEdge R760 8SFF Chassis', type: 'Chassis', quantity: 12, unitPrice: 3250 },
                { id: 'item-mi-cd2', partNumber: '338-CHYT', name: 'Intel Xeon Gold 6430 32-Core CPU', type: 'Processor', quantity: 24, unitPrice: 2190 },
                { id: 'item-mi-cd3', partNumber: '370-AHFF', name: 'Dell 64GB RDIMM 4800MT/s RAM', type: 'Memory', quantity: 96, unitPrice: 595 }
              ]
            }
          ];
        }

        try {
          appendLogEvent('info', 'Connecting direct REST API to dispatch workbook to secure compiler...');
          const response = await fetch('/api/boq/ingest', {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify({ fileName, presetType, rawText })
          });
          
          if (response.ok) {
            const data = await response.json();
            if (data.success && data.solutions) {
              onUpdateBOM(rawText + `\n\n[API METRIC SIGNED] Server verified with ${data.parsedSummary.initialConfidenceScore}% initial confidence score.`);
              onUpdateSolutions(data.solutions);
              appendLogEvent('ok', `[API SECURE LINK] Server parsed "${fileName}" returning ${data.solutions.length} alternative configuration pipelines.`);
              onShowToast(`Workbook parsed by live backend API!`, 'success');
              return;
            }
          }
          throw new Error('API return is unsynced');
        } catch (e) {
          console.warn('API link is unavailable. Reverting gracefully to local sandbox compiler.', e);
          onUpdateBOM(rawText);
          onUpdateSolutions(sols);
          appendLogEvent('info', `Ingested sheet spreadsheet workbook "${fileName}". Matrix processing parsed ${sols[0]?.items?.length || 3} structural component units.`);
          appendLogEvent('ok', `Dual vendor alternatives generated: [${sols.map(s => s.vendor).join(' vs ')}] matching profile constraints.`);
          onShowToast(`Workbook loaded! ${sols[0]?.vendor} alternative dynamically mapped.`, 'success');
        }
      };

      return (
        <div className="space-y-4">
          <p className="text-[11px] text-gray-400 leading-normal font-sans">
            Pricing comparisons and specifications are managed centrally to maintain ledger integrity and avoid multi-file conflicts.
          </p>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
            
            {/* Left side: Central Ingestion Hub Pointer Referral Block */}
            <div className="space-y-3">
              <div className="border border-indigo-500/10 rounded-xl p-5 text-center flex flex-col items-center justify-center gap-3 bg-[#0d1527]/30">
                <UploadCloud className="w-8 h-8 text-sky-400" />
                <div className="space-y-1">
                  <p className="text-xs text-white font-semibold">Central Ingest Protocol Active</p>
                  <p className="text-[10px] text-gray-400 max-w-xs leading-relaxed mx-auto">
                    Spreadsheet uploads, Excel parser API streams, and manufacturer BOM reconciliations are handled exclusively inside the dedicated **BOQ & BOM Ingest Hub** tab.
                  </p>
                </div>

                <button
                  type="button"
                  onClick={() => {
                    const sidebarBtn = document.getElementById('nav-ingestion-hub');
                    if (sidebarBtn) {
                      sidebarBtn.click();
                    }
                  }}
                  className="mt-1 text-[9px] bg-sky-500/10 hover:bg-sky-500/15 text-sky-400 font-mono font-bold px-3 py-1.5 rounded cursor-pointer border border-sky-500/20 hover:border-sky-500/40 uppercase tracking-wide inline-block transition focus:outline-none"
                >
                  📥 Open BOQ & BOM Ingest Hub
                </button>
              </div>

              {/* Presets simulator */}
              <div className="p-3.5 rounded-xl border bg-[#0b1220]/50 border-white/5 space-y-2 text-left">
                <span className="text-[9.5px] uppercase font-bold text-indigo-400 tracking-wider flex items-center gap-1">
                  <Sparkles className="w-3 h-3 text-indigo-300 animate-pulse" /> Fast Simulator Ingestion Fallback
                </span>
                <p className="text-[10px] text-gray-400 leading-normal font-sans">
                  Instantly trigger mock pricing parameters for this active UCID from standard pre-configured baseline models:
                </p>
                <div className="grid grid-cols-3 gap-2 pt-1">
                  <button
                    type="button"
                    onClick={() => handleSimulateIntake('HPE_PARTNER_QUOTE_6130_EOL.xlsx', 'hpe-legacy')}
                    className="p-1.5 rounded bg-amber-500/10 hover:bg-amber-500/15 border border-amber-500/20 text-amber-400 text-left font-mono text-[9px] cursor-pointer transition flex flex-col justify-between h-14"
                  >
                    <span className="font-extrabold uppercase text-[7.5px] text-amber-500 mb-0.5">● HPE EOL SKU</span>
                    <span className="text-gray-300 text-[8px] truncate max-w-full">6130 Legacy CPU</span>
                  </button>
                  <button
                    type="button"
                    onClick={() => handleSimulateIntake('DELL_PREMIER_QUOTE_DRAFT.csv', 'dell-overcharge')}
                    className="p-1.5 rounded bg-rose-500/10 hover:bg-rose-500/15 border border-rose-500/20 text-rose-400 text-left font-mono text-[9px] cursor-pointer transition flex flex-col justify-between h-14"
                  >
                    <span className="font-extrabold uppercase text-[7.5px] text-rose-500 mb-0.5">● Dell Markup</span>
                    <span className="text-gray-300 text-[8px] truncate max-w-full">Overprice storage</span>
                  </button>
                  <button
                    type="button"
                    onClick={() => handleSimulateIntake('CISCO_UCS_AS_SYMMETRICAL.csv', 'cisco-asymmetry')}
                    className="p-1.5 rounded bg-purple-500/10 hover:bg-purple-500/15 border border-purple-500/20 text-purple-400 text-left font-mono text-[9px] cursor-pointer transition flex flex-col justify-between h-14"
                  >
                    <span className="font-extrabold uppercase text-[7.5px] text-purple-500 mb-0.5">● Cisco Symmetry</span>
                    <span className="text-gray-300 text-[8px] truncate max-w-full">Asymmetric RAM</span>
                  </button>
                </div>
              </div>
            </div>

            {/* Right side: Interactive Spec Sheet TextArea */}
            <div className="flex flex-col gap-2 text-left">
              <span className="text-[10px] text-gray-400 font-bold uppercase tracking-wider">Specifications/Workbook Text Dump</span>
              <textarea
                id="raw-bom-textarea"
                value={ucid.rawBOM}
                onChange={(e) => onUpdateBOM(e.target.value)}
                className="w-full flex-1 min-h-[140px] p-3 rounded-lg border text-[10.5px] font-mono text-[#00d4a0] placeholder-gray-500 focus:outline-none focus:ring-1 focus:ring-indigo-500/30 bg-black/35 border-white/10"
              />
            </div>
            
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2 border-t border-white/5">
            <div className="p-2.5 border rounded-lg space-y-1 text-left bg-[#070a13] border-indigo-500/10">
              <p className="text-[10.5px] font-bold text-white uppercase tracking-wider">Estimated Specs Extracted</p>
              {ucid.solutions && ucid.solutions.length > 0 ? (
                <div className="text-[11px] text-indigo-400 space-y-0.5 font-mono">
                  <p>✓ Active solutions linked: <span className="text-white font-bold">{ucid.solutions.length} alternative designs</span></p>
                  <p>✓ Current parsed items count: <span className="text-white font-bold">
                    {ucid.solutions[0]?.items?.reduce((s, it) => s + it.quantity, 0) || 0} hardware components
                  </span></p>
                </div>
              ) : (
                <ul className="text-[11px] text-gray-500 space-y-1">
                  <li>• Awaiting workbook drop or pasted specification file to parse hardware matrix items</li>
                  <li>• Extracted components are mapped across partner catalogs immediately</li>
                </ul>
              )}
            </div>
            <div className="flex flex-col justify-end">
              <button
                id="btn-advance-to-scan"
                type="button"
                onClick={onAdvance}
                className="w-full md:w-auto self-end flex items-center justify-center gap-2 text-xs font-bold px-4 py-2.5 rounded-lg bg-indigo-500 text-white hover:bg-indigo-600 transition-all cursor-pointer shadow-lg shadow-indigo-500/10 uppercase tracking-wide"
              >
                Launch Intelligence Scan <ArrowRight className="w-4 h-4 text-white" />
              </button>
            </div>
          </div>
        </div>
      );
    }

    case 'pre-intelligence':
      return (
        <div className="space-y-4">
          <p className="text-xs text-gray-400 leading-normal text-left">
            Cross-examine raw input lines against vendor partner catalogs (HPE, Dell, Cisco). This resolves naming ambiguities (e.g., matching "32-Core CPU" to "Intel Gold 6430").
          </p>
          {isRunning ? (
            <div className="p-6 border rounded-lg flex flex-col items-center justify-center gap-3 bg-[#070a13] border-indigo-500/10">
              <RefreshCw className="w-6 h-6 text-indigo-400 animate-spin" />
              <div className="w-64 h-1.5 bg-gray-800 rounded-full overflow-hidden">
                <div className="h-full bg-indigo-400 transition-all duration-150" style={{ width: `${intelProgress}%` }} />
              </div>
              <span className="text-[11px] text-gray-400 font-mono">Catalog sync: {intelProgress}% completed...</span>
            </div>
          ) : ucid.solutions.length > 0 ? (
            <div className="p-3 border rounded-lg border-[#00d4a0]/20 bg-[#00d4a0]/5 flex items-center justify-between">
              <div className="flex items-center gap-3">
                <CheckCircle className="w-5 h-5 text-[#00d4a0]" />
                <div className="text-left">
                  <p className="text-xs text-white font-bold">Intelligence Scan Synthesized</p>
                  <p className="text-[10px] text-gray-500">Dual design models compiled (HPE DL380 Alternative & Dell R760 Alternative).</p>
                </div>
              </div>
              <button onClick={onAdvance} className="text-xs px-3 py-1.5 bg-indigo-500 text-white rounded font-bold cursor-pointer hover:bg-indigo-600">
                Inspect Alternative Architectures
              </button>
            </div>
          ) : (
            <button
              id="btn-run-catalog-scan"
              type="button"
              onClick={onRunIntel}
              className="flex items-center gap-2 text-xs font-bold px-4 py-2.5 rounded-lg bg-indigo-500 text-white hover:bg-indigo-600 cursor-pointer shadow-lg shadow-indigo-500/10"
            >
              <Zap className="w-4 h-4 text-yellow-400 animate-pulse" /> Run Vendor Catalog Intelligence Scan
            </button>
          )}
        </div>
      );

    case 'solution-design':
      return (
        <div className="space-y-4">
          <p className="text-xs text-gray-400 leading-normal text-left">
            Dual-Sourced Configurations constructed by our procurement intelligence parser. Customize component lists.
          </p>
          {ucid.solutions.length === 0 ? (
            <p className="text-xs text-gray-500 italic text-left">No designs have been prepared. Run Catalog Intelligence first.</p>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              {ucid.solutions.map((sol, idx) => (
                <SolutionConfigCard
                  key={sol.id}
                  solution={sol}
                  index={idx}
                  onUpdate={(updatedSol) => {
                    const nextSols = ucid.solutions.map(s => s.id === updatedSol.id ? updatedSol : s);
                    onUpdateSolutions(nextSols);
                    appendLogEvent('info', `Config modified count for ${sol.vendor} is adjusted.`);
                  }}
                />
              ))}
            </div>
          )}
          <div className="flex justify-end pt-2">
            <button
              type="button"
              onClick={onAdvance}
              className="flex items-center gap-2 text-xs font-bold px-4 py-2.5 rounded-lg bg-indigo-500 text-white hover:bg-indigo-600 cursor-pointer"
            >
              Secure Transactional API Quotes <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      );

    case 'vendor-provisioning':
      return (
        <div className="space-y-4">
          <p className="text-xs text-gray-400 leading-normal text-left">
            Sourcing live contract rates via secure authenticated REST/SOAP APIs directly from Hewlett Packard Enterprise & Dell.
          </p>
          <div className="space-y-3">
            <div className="p-3.5 rounded-xl border flex flex-col md:flex-row md:items-center justify-between gap-4 bg-[#070a13] border-indigo-500/10 text-left">
              <div>
                <span className="text-[10px] font-mono text-[#00d4a0] font-bold uppercase">HPE Quote Gateway</span>
                <p className="text-[11px] text-white font-medium mt-1">Status: SECURE CONTRACT RATE APPLIED (-6.2% base)</p>
                <p className="text-[10px] text-gray-500 mt-0.5">Reference quote hash: hpe-q-2026-9281a</p>
              </div>
              <span className="text-[10px] font-mono text-gray-400">Latency: 28 ms</span>
            </div>

            <div className="p-3.5 rounded-xl border flex flex-col md:flex-row md:items-center justify-between gap-4 bg-[#070a13] border-indigo-500/10 text-left">
              <div>
                <span className="text-[10px] font-mono text-[#4a85fd] font-bold uppercase">Dell Direct Quote Channel</span>
                <p className="text-[11px] text-white font-medium mt-1">Status: MATCHED CUSTOM VOLUME CONTRACT DISCOUNT (-6.6% bulk applied)</p>
                <p className="text-[10px] text-gray-500 mt-0.5">Reference quote hash: dell-q-8841x-v6</p>
              </div>
              <span className="text-[10px] font-mono text-gray-400">Latency: 42 ms</span>
            </div>
          </div>
          <div className="flex justify-end pt-2">
            <button
              type="button"
              onClick={onAdvance}
              className="flex items-center gap-2 text-xs font-bold px-4 py-2.5 rounded-lg bg-indigo-500 text-white hover:bg-indigo-600 cursor-pointer"
            >
              Verify Technical Constraints <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      );

    case 'post-intelligence':
      return (
        <div className="space-y-4">
          <p className="text-xs text-gray-400 leading-normal text-left">
            Validating deep architectural rules: checking system load thresholds, power dissipation, module-socket layouts, and EOL components.
          </p>
          <div className="p-3 rounded-lg border border-yellow-500/20 bg-yellow-500/5 space-y-2 text-left">
            <div className="flex items-center gap-2 text-xs text-yellow-500 font-bold">
              <AlertTriangle className="w-4 h-4" /> Technical Rule Recommendation Mismatch
            </div>
            <p className="text-[11px] text-gray-400 leading-normal">
              Processor Intel Xeon Gold configuration operates on octa-channel memory structures. Your RAM quantity matches ideal specifications.
            </p>
          </div>
          <div className="flex items-center justify-between pt-2">
            <button
              type="button"
              onClick={() => appendLogEvent('ok', 'Intel rule checked: 8-channel socket layout is fully balanced.')}
              className="text-xs px-3 py-1.5 rounded bg-indigo-500/10 text-indigo-400 border border-indigo-500/20 font-semibold hover:bg-indigo-500/15 cursor-pointer"
            >
              Override Layout Alarm
            </button>
            <button
              type="button"
              onClick={onAdvance}
              className="flex items-center gap-2 text-xs font-bold px-4 py-2.5 rounded-lg bg-indigo-500 text-white hover:bg-indigo-600 cursor-pointer"
            >
              Proceed to Cost Comparison <ArrowRight className="w-4 h-4" />
            </button>
          </div>
        </div>
      );

    case 'comparison':
      return (
        <div className="space-y-4">
          <p className="text-xs text-gray-400 leading-normal text-left">
            Cross-compare dual alternative metrics. Mark a chosen vendor as the active choice to freeze their respective Bill of Materials design as the winner.
          </p>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {ucid.solutions.map((sol, solIdx) => {
              const isActiveChoice = solIdx === 0;
              return (
                <div 
                  key={sol.id} 
                  className={`p-4 rounded-xl border flex flex-col justify-between gap-3 transition-all duration-300 ${
                    isActiveChoice ? 'bg-indigo-600/5 border-indigo-500 shadow-lg shadow-indigo-500/5' : 'bg-[#070a13] border-white/5 opacity-80'
                  }`}
                >
                  <div className="space-y-3 text-left">
                    <div className="flex justify-between items-center">
                      <span className="text-xs font-bold text-white uppercase tracking-wider">{sol.vendor} Alternative Selection</span>
                      <span className="text-[10px] text-[#00d4a0] font-bold bg-[#00d4a0]/10 px-2 py-0.5 rounded-full">
                        {sol.complianceScore}% compliant
                      </span>
                    </div>
                    <div>
                      <p className="text-lg font-bold text-white">${sol.totalPrice.toLocaleString()}</p>
                      <p className="text-[10px] text-gray-500">Original price: <span className="line-through">${sol.originalPrice.toLocaleString()}</span> (saved ${sol.savings.toLocaleString()})</p>
                    </div>
                    <div className="text-[11px] text-gray-400 space-y-1">
                      <p>• Estimated lead time: <span className="text-white font-medium">7–12 business days</span></p>
                      <p>• Shipping fee: <span className="text-green-400 font-medium">Included (connected direct partner discount)</span></p>
                      <p>• Warranty structure: <span className="text-white font-semibold">3-Year Factory Carepack</span></p>
                    </div>
                  </div>

                  {/* Active Selection Indicator button */}
                  <div className="mt-2 pt-2.5 border-t border-white/5 flex justify-end">
                    {isActiveChoice ? (
                      <span className="flex items-center gap-1 text-[9.5px] uppercase font-black text-[#00d4a0] bg-[#00d4a0]/10 border border-[#00d4a0]/25 px-2.5 py-1 rounded">
                        <Check className="w-3.5 h-3.5 text-[#00d4a0]" /> Active Choice
                      </span>
                    ) : (
                      <button
                        type="button"
                        onClick={() => {
                          const idx = ucid.solutions.findIndex(s => s.id === sol.id);
                          if (idx !== -1) {
                            const reordered = [...ucid.solutions];
                            const selectedSol = reordered[idx];
                            reordered.splice(idx, 1);
                            reordered.unshift(selectedSol);
                            onUpdateSolutions(reordered);
                            appendLogEvent('ok', `Set ${sol.vendor} alternative to active choice.`);
                          }
                        }}
                        className="px-2.5 py-1 text-[9px] uppercase font-bold text-indigo-400 bg-indigo-500/10 hover:bg-indigo-500/15 border border-indigo-500/20 rounded cursor-pointer transition"
                      >
                        Select Sourcing Winner
                      </button>
                    )}
                  </div>
                </div>
              );
            })}
          </div>

          {/* Sourcing side-by-side spec alignment diff table */}
          {ucid.solutions.length >= 2 && (
            <SourcingReconciliationDiff solutions={ucid.solutions} />
          )}

          <div className="border-t pt-4 flex flex-col md:flex-row md:items-center justify-between gap-4 border-indigo-500/10 text-left">
            <span className="text-xs text-gray-500">Choosing the winner will generate a final digital snap PO for sign-off.</span>
            {committingSnapshot ? (
              <button type="button" className="flex items-center gap-2 text-xs font-bold px-4 py-2.5 rounded-lg bg-[#00d4a0]/20 text-[#00d4a0] border border-[#00d4a0]/30 cursor-not-allowed">
                <RefreshCw className="w-3.5 h-3.5 animate-spin" /> Locking snapshot...
              </button>
            ) : (
              <button
                type="button"
                onClick={onCommitSnapshot}
                className="flex items-center gap-2 text-xs font-bold px-4 py-2.5 rounded-lg bg-[#00d4a0] text-gray-950 font-extrabold hover:opacity-90 transition-all cursor-pointer shadow-lg shadow-[#00d4a0]/10"
              >
                <CheckCircle className="w-4 h-4 text-gray-950" /> Freeze & Commit Design Snapshot
              </button>
            )}
          </div>
        </div>
      );

    case 'snapshot':
      return (
        <div className="space-y-4">
          <div className="p-4 border border-[#00d4a0]/20 bg-[#00d4a0]/5 rounded-xl space-y-3">
            <div className="flex items-center gap-2.5 text-left">
              <div className="w-8 h-8 rounded-full bg-[#00d4a0]/10 flex items-center justify-center">
                <CheckCircle className="w-5 h-5 text-[#00d4a0]" />
              </div>
              <div>
                <p className="text-xs text-white font-bold uppercase">Locked PO & Sourcing Ledger Committed</p>
                <p className="text-[10px] text-gray-500">This UCID transaction pipeline is fully synced and archived.</p>
              </div>
            </div>

            <div className="border-t pt-3 space-y-2 border-[#00d4a0]/10 text-left">
              {ucid.snapshots.map((snap) => (
                <div key={snap.id} className="text-[11px] space-y-1 bg-black/30 p-2.5 rounded-lg">
                  <div className="flex items-center justify-between">
                    <span className="text-white font-semibold font-sans">{snap.label}</span>
                    <span className="text-gray-500 font-mono text-[9px]">{snap.committedAt}</span>
                  </div>
                  <p className="text-gray-400">Winner Source: <span className="text-[#00d4a0] font-bold">{snap.winnerSolution}</span></p>
                  <p className="text-gray-400">Contract Total: <span className="text-xs text-white font-bold">${snap.totalValue.toLocaleString()}</span></p>
                  <p className="text-gray-500 mt-1 italic text-[10px]">Notes: {snap.notes}</p>
                </div>
              ))}
            </div>
          </div>

          <div className="flex gap-2 justify-start">
            <button
              type="button"
              onClick={() => {
                onShowToast("Generating local Bill of Materials (BOM) Excel spreadsheet file download...", "success");
                try {
                  const rows: any[] = [];
                  
                  // Map active solutions and nested items into structured worksheet rows
                  if (ucid && ucid.solutions && ucid.solutions.length > 0) {
                    ucid.solutions.forEach((sol) => {
                      if (sol.items && sol.items.length > 0) {
                        sol.items.forEach((item) => {
                          rows.push({
                            'Vendor Model': sol.vendor,
                            'Proposal Title': sol.label,
                            'Proposal Price Total ($)': sol.totalPrice,
                            'Compliance Rating (%)': sol.complianceScore,
                            'Target Manufacturer Part Number': item.partNumber,
                            'Equipment Item Sourced Name': item.name,
                            'Equipment Category Type': item.type,
                            'Allocated Quantity': item.quantity,
                            'Supplier Unit Price ($)': item.unitPrice,
                            'Extended Subtotal ($)': item.quantity * item.unitPrice
                          });
                        });
                      }
                    });
                  } else {
                    rows.push({
                      'UCID Index Number': ucid.displayId,
                      'Project Reference Name': ucid.name,
                      'Priority Level': ucid.priority,
                      'Current Phase': ucid.currentStep,
                      'Synchronization Status': ucid.syncStatus || 'Pending',
                      'Fulfillment Note': 'No partner vendor design alternatives generated or ingest failed'
                    });
                  }

                  const worksheet = XLSX.utils.json_to_sheet(rows);
                  const workbook = XLSX.utils.book_new();
                  XLSX.utils.book_append_sheet(workbook, worksheet, "Procurement Bill of Materials");
                  
                  // Trigger direct browser file write stream
                  XLSX.writeFile(workbook, `${ucid.displayId}_Procurement_BOM_Catalog.xlsx`);
                  appendLogEvent('ok', `Successfully exported structural spreadsheet: ${ucid.displayId}_Procurement_BOM_Catalog.xlsx`);
                  onShowToast("Excel BOM spreadsheet successfully compiled and downloaded!", "success");
                } catch (e: any) {
                  onShowToast(`Failed to parse workbook layout: ${e.message}`, "error");
                }
              }}
              className="flex items-center gap-1 text-xs px-3 py-2 bg-[#070a13] text-gray-300 hover:text-white rounded border border-white/5 cursor-pointer font-bold"
            >
              <FileSpreadsheet className="w-3.5 h-3.5 text-green-400" /> Export Excel BOM
            </button>
            <button
              type="button"
              onClick={() => {
                onShowToast("Compiling and packaging high-fidelity PDF/HTML Proposal document...", "success");
                try {
                  const title = `========================================================================\n` +
                                `   VSIP platform - CONTRACT PROPOSAL & AUDIT CERTIFICATE\n` +
                                `========================================================================\n` +
                                `Date generated: ${new Date().toISOString()}\n` +
                                `Unified Configuration Identifier: ${ucid.displayId}\n` +
                                `Client Active Opportunity Reference: ${ucid.projectRef}\n` +
                                `Sourcing Layout Name: ${ucid.name}\n` +
                                `Ingestion Priority Level: ${ucid.priority.toUpperCase()}\n` +
                                `------------------------------------------------------------------------\n\n` +
                                `1. COMPLIANT ALTERNATIVES & FINANCIAL PERFORMANCE DECK:\n\n`;
                  
                  let solutionsContent = '';
                  if (ucid && ucid.solutions && ucid.solutions.length > 0) {
                    ucid.solutions.forEach((sol, sIdx) => {
                      solutionsContent += `[PROPOSAL #${sIdx + 1}] Brand: ${sol.vendor} - ${sol.label}\n` +
                                          `  ├── Sourced Contract Cost: $${sol.totalPrice.toLocaleString()} USD\n` +
                                          `  ├── Pre-discount Catalogue MSRP: $${sol.originalPrice.toLocaleString()} USD\n` +
                                          `  ├── Contract Direct Savings: $${sol.savings.toLocaleString()} USD\n` +
                                          `  ├── Compliance Health Rating: ${sol.complianceScore}%\n` +
                                          `  └── BOM Configuration Lines:\n`;
                      if (sol.items && sol.items.length > 0) {
                        sol.items.forEach((item) => {
                          solutionsContent += `      * ${item.partNumber} | ${item.name} (${item.type}) x${item.quantity} - Unit: $${item.unitPrice} / Extended: $${(item.quantity * item.unitPrice).toLocaleString()}\n`;
                        });
                      } else {
                        solutionsContent += `      No hardware lines defined.\n`;
                      }
                      solutionsContent += `\n`;
                    });
                  } else {
                    solutionsContent += `No solutions available for compilation in current state.\n\n`;
                  }

                  const auditTrail = `------------------------------------------------------------------------\n` +
                                     `2. INTEGRITY VERIFICATION LOG & TELEMETRY REGISTRY EVENTS:\n\n` +
                                     (ucid.events && ucid.events.length > 0 
                                      ? ucid.events.map(ev => `[${ev.ts}] [${ev.level.toUpperCase()}] ${ev.msg}`).join('\n')
                                      : 'No events logged in the audit database.') + '\n\n' +
                                     `========================================================================\n` +
                                     `                        END OF CERTIFIED DOCUMENT\n` +
                                     `========================================================================\n`;

                  const combinedText = title + solutionsContent + auditTrail;
                  const blob = new Blob([combinedText], { type: 'text/plain;charset=utf-8' });
                  const element = document.createElement('a');
                  element.href = URL.createObjectURL(blob);
                  element.download = `${ucid.displayId}_Procurement_Proposal_Report.txt`;
                  document.body.appendChild(element);
                  element.click();
                  document.body.removeChild(element);

                  appendLogEvent('ok', `Successfully exported compiled text-proposal document: ${ucid.displayId}_Procurement_Proposal_Report.txt`);
                  onShowToast("Proposal document compiled and downloaded successfully!", "success");
                } catch (err: any) {
                  onShowToast(`Failed to generate document: ${err.message}`, "error");
                }
              }}
              className="flex items-center gap-1 text-xs px-3 py-2 bg-[#070a13] text-gray-300 hover:text-white rounded border border-white/5 cursor-pointer font-bold"
            >
              <Download className="w-3.5 h-3.5 text-[#4a85fd]" /> Download PDF Proposal
            </button>
          </div>
        </div>
      );

    default:
      return null;
  }
}
