import React from "react";
import { UploadCloud, Sparkles, ArrowRight } from "lucide-react";
import type { UCID, Solution } from "../../../types";

interface StepBoqIntakeProps {
  ucid: UCID;
  onUpdateBOM: (rawText: string) => void;
  onUpdateSolutions: (sols: Solution[]) => void;
  appendLogEvent: (level: "info" | "warn" | "ok" | "err", msg: string) => void;
  onShowToast: (msg: string, type: "success" | "warn" | "error") => void;
  onAdvance: () => void;
}

export function StepBoqIntake({
  ucid,
  onUpdateBOM,
  onUpdateSolutions,
  appendLogEvent,
  onShowToast,
  onAdvance,
}: StepBoqIntakeProps) {
  const handleSimulateIntake = async (
    fileName: string,
    presetType: "hpe-legacy" | "dell-overcharge" | "cisco-asymmetry",
  ) => {
    let rawText = "";
    let sols: Solution[] = [];

    if (presetType === "hpe-legacy") {
      rawText = `[AUTOMATED WORKBOOK INGESTION - HPE LOGGED QUOTE]\nFile: HPE_PARTNER_QUOTE_6130_EOL.xlsx\nTarget Chassis: DL380 Gen11 NC SFF (P40411-B21) x10 Units\nProcessed CPU SKU: 815100-B21 (Intel Xeon Gold 6130 Legacy CPU) x20 Units\nMemory DIMM RAM: P38454-B21 (64GB DDR5) x80 Units\n\nNotes: Lead duration set to 45 Days due to obsolete processor SKU.`;

      sols = [
        {
          id: `sol-manual-hpe-${Date.now()}`,
          name: "HPE Alternative (Ingested: HPE_PARTNER_QUOTE_6130_EOL.xlsx)",
          targetUcidId: "unknown",
          vendorSubmissions: [
            {
              id: `vs-manual-hpe-${Date.now()}`,
              vendor: "HPE",
              label:
                "HPE Alternative (Ingested: HPE_PARTNER_QUOTE_6130_EOL.xlsx)",
              totalPrice: 118200,
              originalPrice: 125000,
              savings: 6800,
              complianceScore: 78,
              configs: [
                {
                  id: "cfg-1",
                  name: "Auto-Config",
                  totalPrice: 118200,
                  originalPrice: 125000,
                  savings: 6800,
                  items: [
                    {
                      id: "item-mi-1",
                      partNumber: "P40411-B21",
                      name: "HPE ProLiant DL380 Gen11 CTO Chassis",
                      type: "Chassis",
                      quantity: 10,
                      unitPrice: 3400,
                    },
                    {
                      id: "item-mi-2",
                      partNumber: "815100-B21",
                      name: "Intel Xeon Gold 6130 Processor [EOL Sourcing Risk]",
                      type: "Processor",
                      quantity: 20,
                      unitPrice: 1890,
                    },
                    {
                      id: "item-mi-3",
                      partNumber: "P38454-B21",
                      name: "HPE 64GB DDR5 memory module RDIMM",
                      type: "Memory",
                      quantity: 80,
                      unitPrice: 580,
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          id: `sol-manual-dell-${Date.now()}`,
          name: "Dell Alternative (Autogenerated Peer Modern Equivalent)",
          targetUcidId: "unknown",
          vendorSubmissions: [
            {
              id: `vs-manual-dell-${Date.now()}`,
              vendor: "Dell",
              label: "Dell Alternative (Autogenerated Peer Modern Equivalent)",
              totalPrice: 120100,
              originalPrice: 125200,
              savings: 5100,
              complianceScore: 98,
              configs: [
                {
                  id: "cfg-2",
                  name: "Auto-Config",
                  totalPrice: 120100,
                  originalPrice: 125200,
                  savings: 5100,
                  items: [
                    {
                      id: "item-mi-d1",
                      partNumber: "210-BFXS",
                      name: "Dell PowerEdge R760 8SFF Chassis",
                      type: "Chassis",
                      quantity: 10,
                      unitPrice: 3250,
                    },
                    {
                      id: "item-mi-d2",
                      partNumber: "338-CHYT",
                      name: "Intel Xeon Gold 6430 32-Core CPU",
                      type: "Processor",
                      quantity: 20,
                      unitPrice: 2190,
                    },
                    {
                      id: "item-mi-d3",
                      partNumber: "370-AHFF",
                      name: "Dell 64GB RDIMM 4800MT/s RAM",
                      type: "Memory",
                      quantity: 40,
                      unitPrice: 595,
                    },
                  ],
                },
              ],
            },
          ],
        },
      ];
    } else if (presetType === "dell-overcharge") {
      rawText = `[AUTOMATED WORKBOOK INGESTION - DELL PREMIER PORTAL]\nFile: DELL_PREMIER_QUOTE_DRAFT.csv\nTarget Chassis: Dell PowerEdge R760 8SFF (210-BFXS) x12 Units\nStorage Drive SKU: 400-BPSB (Dell 3.84TB SAS Read Intensive SSD SFF) x24 Units [Mark-up: quote price is $1,590 vs contract $1,190]\nMemory: 370-AHFF (64GB RDIMM DDR5) x48 Units`;

      sols = [
        {
          id: `sol-manual-dell-${Date.now()}`,
          name: "Dell Alternative (Ingested: DELL_PREMIER_QUOTE_DRAFT.csv)",
          targetUcidId: "unknown",
          vendorSubmissions: [
            {
              id: `vs-manual-dell-${Date.now()}`,
              vendor: "Dell",
              label:
                "Dell Alternative (Ingested: DELL_PREMIER_QUOTE_DRAFT.csv)",
              totalPrice: 105720,
              originalPrice: 115000,
              savings: 9280,
              complianceScore: 85,
              configs: [
                {
                  id: "cfg-de-1",
                  name: "Auto-Config",
                  totalPrice: 105720,
                  originalPrice: 115000,
                  savings: 9280,
                  items: [
                    {
                      id: "item-mi-de1",
                      partNumber: "210-BFXS",
                      name: "Dell PowerEdge R760 8SFF Chassis Base Unit",
                      type: "Chassis",
                      quantity: 12,
                      unitPrice: 3250,
                    },
                    {
                      id: "item-mi-de2",
                      partNumber: "400-BPSB",
                      name: "Dell 3.84TB SAS Read Intensive SSD SFF [Markup Variance]",
                      type: "Drive",
                      quantity: 24,
                      unitPrice: 1590,
                    },
                    {
                      id: "item-mi-de3",
                      partNumber: "370-AHFF",
                      name: "Dell 64GB RDIMM 4800MT/s memory module",
                      type: "Memory",
                      quantity: 48,
                      unitPrice: 595,
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          id: `sol-manual-hpe-${Date.now()}`,
          name: "HPE Alternative (Autogenerated Peer Base)",
          targetUcidId: "unknown",
          vendorSubmissions: [
            {
              id: `vs-manual-hpe-${Date.now()}`,
              vendor: "HPE",
              label: "HPE Alternative (Autogenerated Peer Base)",
              totalPrice: 98160,
              originalPrice: 110000,
              savings: 11840,
              complianceScore: 98,
              configs: [
                {
                  id: "cfg-hpe-1",
                  name: "Auto-Config",
                  totalPrice: 98160,
                  originalPrice: 110000,
                  savings: 11840,
                  items: [
                    {
                      id: "item-mi-h1",
                      partNumber: "P40411-B21",
                      name: "HPE ProLiant DL380 Gen11 8SFF Chassis",
                      type: "Chassis",
                      quantity: 12,
                      unitPrice: 3400,
                    },
                    {
                      id: "item-mi-h2",
                      partNumber: "P40483-B21",
                      name: "HPE 3.84TB NVMe SSD Sourced",
                      type: "Drive",
                      quantity: 24,
                      unitPrice: 1220,
                    },
                    {
                      id: "item-mi-h3",
                      partNumber: "P38454-B21",
                      name: "HPE 64GB Dual Rank DDR5 module",
                      type: "Memory",
                      quantity: 48,
                      unitPrice: 580,
                    },
                  ],
                },
              ],
            },
          ],
        },
      ];
    } else {
      rawText = `[AUTOMATED WORKBOOK INGESTION - CISCO MATRIX CHALLENGE]\nFile: CISCO_UCS_AS_SYMMETRICAL.csv\nTarget Chassis: UCS C240 M7 Rack Server (UCSC-C240-M7S) x12 Units\nProcessor Unit: UCS-CPU-I6430 x24 Units\nMemory Allocation: UCS-MR-64G2ED-E (Cisco 64GB DDR5 RDIMM) x5 modules/node [Total Qty: 60 units]`;

      sols = [
        {
          id: `sol-manual-cisco-${Date.now()}`,
          name: "Cisco Alternative (Ingested: CISCO_UCS_AS_SYMMETRICAL.csv)",
          targetUcidId: "unknown",
          vendorSubmissions: [
            {
              id: `vs-manual-cisco-${Date.now()}`,
              vendor: "Cisco",
              label:
                "Cisco Alternative (Ingested: CISCO_UCS_AS_SYMMETRICAL.csv)",
              totalPrice: 140520,
              originalPrice: 148000,
              savings: 7480,
              complianceScore: 82,
              configs: [
                {
                  id: "cfg-c1",
                  name: "Auto-Config",
                  totalPrice: 140520,
                  originalPrice: 148000,
                  savings: 7480,
                  items: [
                    {
                      id: "item-mi-c1",
                      partNumber: "UCSC-C240-M7S",
                      name: "Cisco UCS C240 M7 Rack Server Chassis",
                      type: "Chassis",
                      quantity: 12,
                      unitPrice: 4100,
                    },
                    {
                      id: "item-mi-c2",
                      partNumber: "UCS-CPU-I6430",
                      name: "UCS Intel Xeon Gold 6430 32-Core CPU",
                      type: "Processor",
                      quantity: 24,
                      unitPrice: 2280,
                    },
                    {
                      id: "item-mi-c3",
                      partNumber: "UCS-MR-64G2ED-E",
                      name: "UCS 64GB DDR5 memory module [Asymmetric Layout]",
                      type: "Memory",
                      quantity: 60,
                      unitPrice: 610,
                    },
                  ],
                },
              ],
            },
          ],
        },
        {
          id: `sol-manual-dell-${Date.now()}`,
          name: "Dell Alternative (Autogenerated Peer Base)",
          targetUcidId: "unknown",
          vendorSubmissions: [
            {
              id: `vs-manual-dell-${Date.now()}`,
              vendor: "Dell",
              label: "Dell Alternative (Autogenerated Peer Base)",
              totalPrice: 138000,
              originalPrice: 145000,
              savings: 7000,
              complianceScore: 98,
              configs: [
                {
                  id: "cfg-cd1",
                  name: "Auto-Config",
                  totalPrice: 138000,
                  originalPrice: 145000,
                  savings: 7000,
                  items: [
                    {
                      id: "item-mi-cd1",
                      partNumber: "210-BFXS",
                      name: "Dell PowerEdge R760 8SFF Chassis",
                      type: "Chassis",
                      quantity: 12,
                      unitPrice: 3250,
                    },
                    {
                      id: "item-mi-cd2",
                      partNumber: "338-CHYT",
                      name: "Intel Xeon Gold 6430 32-Core CPU",
                      type: "Processor",
                      quantity: 24,
                      unitPrice: 2190,
                    },
                    {
                      id: "item-mi-cd3",
                      partNumber: "370-AHFF",
                      name: "Dell 64GB RDIMM 4800MT/s RAM",
                      type: "Memory",
                      quantity: 96,
                      unitPrice: 595,
                    },
                  ],
                },
              ],
            },
          ],
        },
      ];
    }

    try {
      appendLogEvent(
        "info",
        "Connecting direct REST API to dispatch workbook to secure compiler...",
      );
      const response = await fetch("/api/boq/ingest", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ fileName, presetType, rawText }),
      });

      if (response.ok) {
        const data = await response.json();
        if (data.success && data.solutions) {
          onUpdateBOM(
            rawText +
              `\n\n[API METRIC SIGNED] Server verified with ${data.parsedSummary.initialConfidenceScore}% initial confidence score.`,
          );
          onUpdateSolutions(data.solutions);
          appendLogEvent(
            "ok",
            `[API SECURE LINK] Server parsed "${fileName}" returning ${data.solutions.length} alternative configuration pipelines.`,
          );
          onShowToast(`Workbook parsed by live backend API!`, "success");
          return;
        }
      }
      throw new Error("API return is unsynced");
    } catch (e) {
      console.warn(
        "API link is unavailable. Reverting gracefully to local sandbox compiler.",
        e,
      );
      onUpdateBOM(rawText);
      onUpdateSolutions(sols);
      appendLogEvent(
        "info",
        `Ingested sheet spreadsheet workbook "${fileName}". Matrix processing parsed ${sols[0]?.vendorSubmissions?.[0]?.configs?.[0]?.items?.length || 3} structural component units.`,
      );
      appendLogEvent(
        "ok",
        `Dual vendor alternatives generated: [${sols.flatMap((s) => s.vendorSubmissions?.map((vs) => vs.vendor) || []).join(" vs ")}] matching profile constraints.`,
      );
      onShowToast(
        `Workbook loaded! ${sols[0]?.vendorSubmissions?.[0]?.vendor} alternative dynamically mapped.`,
        "success",
      );
    }
  };

  return (
    <div className="space-y-4">
      {/* Unified Pipeline Active Banner */}
      <div className="p-3 bg-indigo-500/5 border border-indigo-500/20 rounded-xl flex items-center justify-between text-left gap-4">
        <div>
          <span className="text-[9px] font-bold text-indigo-400 font-mono tracking-wider uppercase bg-indigo-500/10 px-2 py-0.5 rounded">
            ● Unified State Sync Active
          </span>
          <p className="text-[11px] text-white font-semibold mt-1">
            Sourcing Ingestion & Opportunity sync
          </p>
          <p className="text-[10px] text-gray-400 mt-0.5 leading-snug">
            Any spreadsheet compiled or simulated here updates the central procurement ledger inside <span className="text-gray-300 font-medium">BOM Reconciliation Diff</span> and maps EOL risks inside <span className="text-gray-300 font-medium">Forensic Scan & Heal</span> instantly.
          </p>
        </div>
        <div className="text-right shrink-0">
          <span className="text-[10px] font-mono text-emerald-400 font-bold block">
            ID: {ucid.displayId}
          </span>
          <span className="text-[9px] text-gray-500 font-sans block mt-0.5">
            Status: Synchronized
          </span>
        </div>
      </div>

      <p className="text-[11px] text-gray-400 leading-normal font-sans">
        Pricing comparisons and specifications are managed centrally to maintain
        ledger integrity and avoid multi-file conflicts.
      </p>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {/* Left side: Central Ingestion Hub Pointer Referral Block */}
        <div className="space-y-3">
          <div className="border border-indigo-500/10 rounded-xl p-5 text-center flex flex-col items-center justify-center gap-3 bg-surface-elevated/30">
            <UploadCloud className="w-8 h-8 text-sky-400" />
            <div className="space-y-1">
              <p className="text-xs text-white font-semibold">
                Central Ingest Protocol Active
              </p>
              <p className="text-[10px] text-gray-400 max-w-xs leading-relaxed mx-auto">
                Spreadsheet uploads, Excel parser API streams, and manufacturer
                BOM reconciliations are handled exclusively inside the dedicated
                **BOQ & BOM Ingest Hub** tab.
              </p>
            </div>

            <button
              type="button"
              onClick={() => {
                const sidebarBtn = document.getElementById("nav-ingestion-hub");
                if (sidebarBtn) {
                  sidebarBtn.click();
                }
              }}
              className="mt-1 text-[9px] bg-sky-500/10 hover:bg-sky-500/15 text-sky-400 font-mono font-bold px-3 py-1.5 rounded cursor-pointer border border-sky-500/20 hover:border-sky-500/40 uppercase tracking-wide inline-block transition focus:outline-none"
            >
              📥 Open BOQ & BOM Ingest Hub
            </button>
          </div>

          {/* Presets simulator */}
          <div className="p-3.5 rounded-xl border bg-surface-elevated/50 border-white/5 space-y-2 text-left">
            <span className="text-[9.5px] uppercase font-bold text-indigo-400 tracking-wider flex items-center gap-1">
              <Sparkles className="w-3 h-3 text-indigo-300 animate-pulse" />{" "}
              Fast Simulator Ingestion Fallback
            </span>
            <p className="text-[10px] text-gray-400 leading-normal font-sans">
              Instantly trigger mock pricing parameters for this active UCID from
              standard pre-configured baseline models:
            </p>
            <div className="grid grid-cols-3 gap-2 pt-1">
              <button
                type="button"
                onClick={() =>
                  handleSimulateIntake(
                    "HPE_PARTNER_QUOTE_6130_EOL.xlsx",
                    "hpe-legacy",
                  )
                }
                className="p-1.5 rounded bg-amber-500/10 hover:bg-amber-500/15 border border-amber-500/20 text-amber-400 text-left font-mono text-[9px] cursor-pointer transition flex flex-col justify-between h-14"
              >
                <span className="font-extrabold uppercase text-[7.5px] text-amber-500 mb-0.5">
                  ● HPE EOL SKU
                </span>
                <span className="text-gray-300 text-[8px] truncate max-w-full">
                  6130 Legacy CPU
                </span>
              </button>
              <button
                type="button"
                onClick={() =>
                  handleSimulateIntake(
                    "DELL_PREMIER_QUOTE_DRAFT.csv",
                    "dell-overcharge",
                  )
                }
                className="p-1.5 rounded bg-rose-500/10 hover:bg-rose-500/15 border border-rose-500/20 text-rose-400 text-left font-mono text-[9px] cursor-pointer transition flex flex-col justify-between h-14"
              >
                <span className="font-extrabold uppercase text-[7.5px] text-rose-500 mb-0.5">
                  ● Dell Markup
                </span>
                <span className="text-gray-300 text-[8px] truncate max-w-full">
                  Overprice storage
                </span>
              </button>
              <button
                type="button"
                onClick={() =>
                  handleSimulateIntake(
                    "CISCO_UCS_AS_SYMMETRICAL.csv",
                    "cisco-asymmetry",
                  )
                }
                className="p-1.5 rounded bg-purple-500/10 hover:bg-purple-500/15 border border-purple-500/20 text-purple-400 text-left font-mono text-[9px] cursor-pointer transition flex flex-col justify-between h-14"
              >
                <span className="font-extrabold uppercase text-[7.5px] text-purple-500 mb-0.5">
                  ● Cisco Symmetry
                </span>
                <span className="text-gray-300 text-[8px] truncate max-w-full">
                  Asymmetric RAM
                </span>
              </button>
            </div>
          </div>
        </div>

        {/* Right side: Interactive Spec Sheet TextArea */}
        <div className="flex flex-col gap-2 text-left">
          <span className="text-[10px] text-gray-400 font-bold uppercase tracking-wider">
            Specifications/Workbook Text Dump
          </span>
          <textarea
            id="raw-bom-textarea"
            value={ucid.rawBOM}
            onChange={(e) => onUpdateBOM(e.target.value)}
            className="w-full flex-1 min-h-[140px] p-3 rounded-lg border text-[10.5px] font-mono text-status-success placeholder-gray-500 focus:outline-none focus:ring-1 focus:ring-indigo-500/30 bg-black/35 border-white/10"
          />
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 pt-2 border-t border-white/5">
        <div className="p-2.5 border rounded-lg space-y-1 text-left bg-surface-card border-indigo-500/10">
          <p className="text-[10.5px] font-bold text-white uppercase tracking-wider">
            Estimated Specs Extracted
          </p>
          {ucid.solutions &&
          ucid.solutions[0]?.vendorSubmissions?.length > 0 ? (
            <div className="text-[11px] text-indigo-400 space-y-0.5 font-mono">
              <p>
                ✓ Active solutions linked:{" "}
                <span className="text-white font-bold">
                  {ucid.solutions[0]?.vendorSubmissions?.length ?? 0}{" "}
                  alternative designs
                </span>
              </p>
              <p>
                ✓ Current parsed items count:{" "}
                <span className="text-white font-bold">
                  {ucid.solutions[0]?.vendorSubmissions?.[0]?.configs
                    ?.flatMap((c) => c.items)
                    ?.reduce((s, it) => s + it.quantity, 0) || 0}{" "}
                  hardware components
                </span>
              </p>
            </div>
          ) : (
            <ul className="text-[11px] text-gray-500 space-y-1">
              <li>
                • Awaiting workbook drop or pasted specification file to parse
                hardware matrix items
              </li>
              <li>
                • Extracted components are mapped across partner catalogs
                immediately
              </li>
            </ul>
          )}
        </div>
        <div className="flex flex-col justify-end">
          <button
            id="btn-advance-to-scan"
            type="button"
            onClick={onAdvance}
            className="w-full md:w-auto self-end flex items-center justify-center gap-2 text-xs font-bold px-4 py-2.5 rounded-lg bg-indigo-500 text-white hover:bg-indigo-600 transition-all cursor-pointer shadow-lg shadow-indigo-500/10 uppercase tracking-wide"
          >
            Launch Intelligence Scan{" "}
            <ArrowRight className="w-4 h-4 text-white" />
          </button>
        </div>
      </div>
    </div>
  );
}
