import { CatalogSKU, UCID, Vendor, Job, UCIDStep, ForensicIssue } from '../../types';
export const catalogSkusPart2: CatalogSKU[] = [
  {
    id: "sku-18",
    vendor: "HPE",
    partNumber: "815100-B21",
    name: "Intel Xeon Gold 6130 16-Core (Legacy Gen10) - EOL",
    type: "Processor",
    price: 1890,
    leadTimeDays: 45,
    status: "eol",
    solution: "Server",
    productFamily: "DL380",
    generation: "Gen10",
  },

  // HPE Items - Storage Solutions (MSA Array System)
  {
    id: "sku-hpe-msa-2060",
    vendor: "HPE",
    partNumber: "R0Q74A",
    name: "HPE MSA 2060 LFF Array Bay Storage Chassis",
    type: "Chassis",
    price: 6800,
    leadTimeDays: 15,
    status: "active",
    solution: "Storage",
    productFamily: "MSA",
    chassisRef: "sku-hpe-msa-2060",
  },
  {
    id: "sku-hpe-msa-ssd",
    vendor: "HPE",
    partNumber: "R0Q37A",
    name: "HPE MSA 1.92TB SAS Read Intensive SFF SSD",
    type: "Drive",
    price: 810,
    leadTimeDays: 8,
    status: "active",
    solution: "Storage",
    productFamily: "MSA",
    chassisRef: "sku-hpe-msa-2060",
  },

  // HPE Items - Networking Solutions (Aruba CX Switches)
  {
    id: "sku-hpe-aruba-10000",
    vendor: "HPE",
    partNumber: "BF100A",
    name: "Aruba CX 10000 48Y6C Distributed Services Switch Chassis System",
    type: "Chassis",
    price: 22400,
    leadTimeDays: 25,
    status: "active",
    solution: "Networking",
    productFamily: "Aruba",
    chassisRef: "sku-hpe-aruba-10000",
  },
  {
    id: "sku-hpe-aruba-transceiver",
    vendor: "HPE",
    partNumber: "1973A",
    name: "Aruba 10G SFP+ to SFP+ 3m Direct Attach Copper Cable",
    type: "Network Adapter",
    price: 140,
    leadTimeDays: 2,
    status: "active",
    solution: "Networking",
    productFamily: "Aruba",
    chassisRef: "sku-hpe-aruba-10000",
  },

  // Dell Items
  {
    id: "sku-6",
    vendor: "Dell",
    partNumber: "338-CHYT",
    name: "Intel Xeon Gold 6430 32-Core 2.1GHz Processor (Dell Equivalent)",
    type: "Processor",
    price: 2190,
    leadTimeDays: 8,
    status: "active",
    solution: "Server",
    productFamily: "R760",
    chassisRef: "sku-9",
  },
  {
    id: "sku-7",
    vendor: "Dell",
    partNumber: "370-AHFF",
    name: "Dell 64GB RDIMM 4800MT/s Dual Rank DDR5 memory",
    type: "Memory",
    price: 595,
    leadTimeDays: 4,
    status: "active",
    solution: "Server",
    productFamily: "R760",
    chassisRef: "sku-9",
  },
  {
    id: "sku-8",
    vendor: "Dell",
    partNumber: "400-BPSB",
    name: "Dell 3.84TB Enterprise NVMe Read Intensive SSD SFF",
    type: "Drive",
    price: 1190,
    leadTimeDays: 10,
    status: "active",
    solution: "Server",
    productFamily: "R760",
    chassisRef: "sku-9",
  },
  {
    id: "sku-9",
    vendor: "Dell",
    partNumber: "210-BFXS",
    name: "Dell PowerEdge R760 8SFF Motherboard & CTO ChassisBaseUnit",
    type: "Chassis",
    price: 3250,
    leadTimeDays: 15,
    status: "active",
    solution: "Server",
    productFamily: "R760",
    chassisRef: "sku-9",
  },
  {
    id: "sku-9-24sff",
    vendor: "Dell",
    partNumber: "210-BFXY",
    name: "Dell PowerEdge R760 24SFF High Density Sourcing Chassis",
    type: "Chassis",
    price: 4100,
    leadTimeDays: 16,
    status: "active",
    solution: "Server",
    productFamily: "R760",
    chassisRef: "sku-9-24sff",
  },
  {
    id: "sku-10",
    vendor: "Dell",
    partNumber: "540-BCOZ",
    name: "Broadcom 57414 Dual Port 10/25Gb SFP28 PCIe Adapter",
    type: "Network Adapter",
    price: 395,
    leadTimeDays: 3,
    status: "active",
    solution: "Server",
    productFamily: "R760",
    chassisRef: "sku-9",
  },
  {
    id: "sku-dell-psu",
    vendor: "Dell",
    partNumber: "450-ADWM",
    name: "Dell Dual Hot-plug Redundant Power Supply (1+1) 1100W",
    type: "Power Supply",
    price: 240,
    leadTimeDays: 4,
    status: "active",
    solution: "Server",
    productFamily: "R760",
    chassisRef: "sku-9",
  },

  // Cisco Items
  {
    id: "sku-11",
    vendor: "Cisco",
    partNumber: "UCS-CPU-I6430",
    name: "UCS Intel Xeon Gold 6430 32-Core CPU",
    type: "Processor",
    price: 2280,
    leadTimeDays: 10,
    status: "active",
    solution: "Server",
    productFamily: "UCS",
    chassisRef: "sku-14",
  },
  {
    id: "sku-12",
    vendor: "Cisco",
    partNumber: "UCS-MR-64G2ED-E",
    name: "UCS 64GB DDR5 memory module RDIMM",
    type: "Memory",
    price: 610,
    leadTimeDays: 6,
    status: "active",
    solution: "Server",
    productFamily: "UCS",
    chassisRef: "sku-14",
  },
  {
    id: "sku-13",
    vendor: "Cisco",
    partNumber: "N20-W6502",
    name: "Cisco Nexus 93180YC-FX3 48-Port Switch Unit",
    type: "Network Adapter",
    price: 14500,
    leadTimeDays: 20,
    status: "active",
    solution: "Networking",
    productFamily: "Nexus",
    chassisRef: "sku-13",
  },
  {
    id: "sku-14",
    vendor: "Cisco",
    partNumber: "UCSC-C240-M7S",
    name: "Cisco UCS C240 M7 Rack Server 2U Chassis Base",
    type: "Chassis",
    price: 4100,
    leadTimeDays: 18,
    status: "active",
    solution: "Server",
    productFamily: "UCS",
    chassisRef: "sku-14",
  },

  // Juniper Items
  {
    id: "sku-15",
    vendor: "Juniper",
    partNumber: "EX3400-48T",
    name: "EX3400 48-port 10/100/1000BaseT Ethernet Switch",
    type: "Network Adapter",
    price: 3800,
    leadTimeDays: 14,
    status: "active",
    solution: "Networking",
    productFamily: "EX",
    chassisRef: "sku-15",
  },
  {
    id: "sku-16",
    vendor: "Juniper",
    partNumber: "QFX5120-48Y",
    name: "QFX5120 48 Port 10G/25G high-performance switch chassis",
    type: "Chassis",
    price: 18400,
    leadTimeDays: 40,
    status: "active",
    solution: "Networking",
    productFamily: "QFX",
    chassisRef: "sku-16",
  },
  {
    id: "sku-17",
    vendor: "Juniper",
    partNumber: "SRX300-SYS-JB",
    name: "SRX300 Services Gateway with JB Care",
    type: "Network Adapter",
    price: 950,
    leadTimeDays: 10,
    status: "active",
    solution: "Networking",
    productFamily: "SRX",
    chassisRef: "sku-17",
  },


];
