import { CatalogSKU} from '../../types';
export const catalogSkusPart1: CatalogSKU[] = [
  // HPE Items - Server Solutions DL380 Gen11
  {
    id: "sku-1",
    vendor: "HPE",
    partNumber: "P40424-B21",
    name: "Intel Xeon Gold 6430 32-Core 2.1GHz Processor (Gen11)",
    type: "Processor",
    price: 2150,
    leadTimeDays: 7,
    status: "active",
    solution: "Server",
    productFamily: "DL380",
    generation: "Gen11",
    chassisRef: "sku-4",
    complianceFlags: {
      taaCompliant: true,
      clicWarning: false,
      regionRestricted: false,
    },
  },
  {
    id: "sku-2",
    vendor: "HPE",
    partNumber: "P38454-B21",
    name: "HPE 64GB Dual Rank x4 DDR5-4800 RAM Module (Gen11)",
    type: "Memory",
    price: 580,
    leadTimeDays: 5,
    status: "active",
    solution: "Server",
    productFamily: "DL380",
    generation: "Gen11",
    chassisRef: "sku-4",
  },
  {
    id: "sku-3",
    vendor: "HPE",
    partNumber: "P40483-B21",
    name: "HPE 3.84TB NVMe Gen4 Read Intensive SFF SSD",
    type: "Drive",
    price: 1220,
    leadTimeDays: 12,
    status: "active",
    solution: "Server",
    productFamily: "DL380",
    generation: "Gen11",
    chassisRef: "sku-4",
  },
  {
    id: "sku-4",
    vendor: "HPE",
    partNumber: "P40411-B21",
    name: "HPE ProLiant DL380 Gen11 8SFF NC CTO Chassis",
    type: "Chassis",
    price: 3400,
    leadTimeDays: 14,
    status: "active",
    solution: "Server",
    productFamily: "DL380",
    generation: "Gen11",
    chassisRef: "sku-4",
  },
  {
    id: "sku-4-24sff",
    vendor: "HPE",
    partNumber: "P40412-B21",
    name: "HPE ProLiant DL380 Gen11 24SFF High Density Chassis",
    type: "Chassis",
    price: 4200,
    leadTimeDays: 15,
    status: "active",
    solution: "Server",
    productFamily: "DL380",
    generation: "Gen11",
    chassisRef: "sku-4-24sff",
  },
  {
    id: "sku-5",
    vendor: "HPE",
    partNumber: "P40445-B21",
    name: "HPE Broadcom 57414 Dual Port 10/25Gb Ethernet Adapter",
    type: "Network Adapter",
    price: 410,
    leadTimeDays: 3,
    status: "active",
    solution: "Server",
    productFamily: "DL380",
    generation: "Gen11",
    chassisRef: "sku-4",
  },
  {
    id: "sku-hpe-psu1",
    vendor: "HPE",
    partNumber: "865414-B21",
    name: "HPE 800W Flex Slot Platinum Hot Plug Low Halogen Power Supply",
    type: "Power Supply",
    price: 195,
    leadTimeDays: 4,
    status: "active",
    solution: "Server",
    productFamily: "DL380",
    generation: "Gen11",
    chassisRef: "sku-4",
  },
  {
    id: "sku-hpe-riser1",
    vendor: "HPE",
    partNumber: "P43019-B21",
    name: "HPE DL380 Gen11 Main PCIe Riser Card Option Kit",
    type: "Riser Card",
    price: 120,
    leadTimeDays: 2,
    status: "active",
    solution: "Server",
    productFamily: "DL380",
    generation: "Gen11",
    chassisRef: "sku-4",
  },
  // HPE Items - Server Solutions DL380 Gen12
  {
    id: "sku-hpe-g12-cpu",
    vendor: "HPE",
    partNumber: "P50123-B21",
    name: "Intel Xeon Platinum 8562Y+ 32-Core 2.8GHz Processor (Gen12)",
    type: "Processor",
    price: 3850,
    leadTimeDays: 9,
    status: "active",
    solution: "Server",
    productFamily: "DL380",
    generation: "Gen12",
    chassisRef: "sku-hpe-dl380-gen12-8sff",
  },
  {
    id: "sku-hpe-g12-ram",
    vendor: "HPE",
    partNumber: "P50164-B21",
    name: "HPE 128GB Quad Rank x4 DDR5-5600 RAM Module (Gen12)",
    type: "Memory",
    price: 1450,
    leadTimeDays: 6,
    status: "active",
    solution: "Server",
    productFamily: "DL380",
    generation: "Gen12",
    chassisRef: "sku-hpe-dl380-gen12-8sff",
  },
  {
    id: "sku-hpe-dl380-gen12-8sff",
    vendor: "HPE",
    partNumber: "P50410-B21",
    name: "HPE ProLiant DL380 Gen12 8SFF High Power Chassis",
    type: "Chassis",
    price: 4500,
    leadTimeDays: 18,
    status: "active",
    solution: "Server",
    productFamily: "DL380",
    generation: "Gen12",
    chassisRef: "sku-hpe-dl380-gen12-8sff",
  },
  {
    id: "sku-hpe-psu2",
    vendor: "HPE",
    partNumber: "P50500-B21",
    name: "HPE 1600W Hot Plug Titanium Power Supply Unit",
    type: "Power Supply",
    price: 310,
    leadTimeDays: 5,
    status: "active",
    solution: "Server",
    productFamily: "DL380",
    generation: "Gen12",
    chassisRef: "sku-hpe-dl380-gen12-8sff",
  },
  // HPE Items - Server Solutions DL380a Gen11 (Accelerator Optimized)
  {
    id: "sku-hpe-dl380a-g11-4dw",
    vendor: "HPE",
    partNumber: "P58410-B21",
    name: "HPE ProLiant DL380a Gen11 4DW Double-Width GPU CTO Chassis",
    type: "Chassis",
    price: 5600,
    leadTimeDays: 20,
    status: "active",
    solution: "Server",
    productFamily: "DL380a",
    generation: "Gen11",
    chassisRef: "sku-hpe-dl380a-g11-4dw",
  },
  {
    id: "sku-hpe-dl380a-gpu",
    vendor: "HPE",
    partNumber: "P58425-B21",
    name: "NVIDIA H100 NVL 80GB GPU PCIe Accelerator Card (DL380a)",
    type: "GPU",
    price: 32500,
    leadTimeDays: 45,
    status: "active",
    solution: "Server",
    productFamily: "DL380a",
    generation: "Gen11",
    chassisRef: "sku-hpe-dl380a-g11-4dw",
  },
  {
    id: "sku-hpe-dl380a-psu",
    vendor: "HPE",
    partNumber: "P58500-B21",
    name: "HPE 2200W Flex Slot Double-Density Hot Plug PSU",
    type: "Power Supply",
    price: 495,
    leadTimeDays: 7,
    status: "active",
    solution: "Server",
    productFamily: "DL380a",
    generation: "Gen11",
    chassisRef: "sku-hpe-dl380a-g11-4dw",
  },
  // HPE Items - Server Solutions DL380 Gen13 Preview Range (Future Roadmap)
  {
    id: "sku-hpe-dl380-gen13-pref",
    vendor: "HPE",
    partNumber: "P70100-B21",
    name: "HPE ProLiant DL380 Gen13 Enterprise Preview Chassis (Roadmap)",
    type: "Chassis",
    price: 5900,
    leadTimeDays: 60,
    status: "active",
    solution: "Server",
    productFamily: "DL380",
    generation: "Gen13",
    chassisRef: "sku-hpe-dl380-gen13-pref",
  },
  {
    id: "sku-hpe-gen13-cpu",
    vendor: "HPE",
    partNumber: "P70125-B21",
    name: "Intel Xeon Platinum 9510 64-Core Next-Gen Processor (Gen13 Preview)",
    type: "Processor",
    price: 6200,
    leadTimeDays: 60,
    status: "active",
    solution: "Server",
    productFamily: "DL380",
    generation: "Gen13",
    chassisRef: "sku-hpe-dl380-gen13-pref",
  },
  // HPE Items - Server Solutions DL80 Family (Gen11 & Gen12)
  {
    id: "sku-hpe-dl80-g11",
    vendor: "HPE",
    partNumber: "847285-B21",
    name: "HPE ProLiant DL80 Gen11 12LFF Storage Optimizer Chassis",
    type: "Chassis",
    price: 2950,
    leadTimeDays: 14,
    status: "active",
    solution: "Server",
    productFamily: "DL80",
    generation: "Gen11",
    chassisRef: "sku-hpe-dl80-g11",
  },
  {
    id: "sku-hpe-dl80-g12",
    vendor: "HPE",
    partNumber: "P60120-B21",
    name: "HPE ProLiant DL80 Gen12 12LFF Pro Base Chassis",
    type: "Chassis",
    price: 3800,
    leadTimeDays: 20,
    status: "active",
    solution: "Server",
    productFamily: "DL80",
    generation: "Gen12",
    chassisRef: "sku-hpe-dl80-g12",
  },
  // Legacy
];