import { CatalogSKU, UCID, Vendor, Job, UCIDStep, ForensicIssue, Solution } from '../../types';
export const mockUcidsPart1: UCID[] = [
  {
    id: "u1",
    displayId: "UCID-2026-0041",
    name: "Scale-Out Compute — 48 Node Intel Virtualisation Cluster",
    solutionName: "North Virtualization Cluster Campaign",
    priority: "high",
    projectRef: "PRJ-VIRT-NORTH-2026",
    createdAt: "2026-06-01 10:24 AM",
    currentStep: "post-intelligence",
    completedSteps: [
      "boq-intake",
      "pre-intelligence",
      "solution-design",
      "vendor-provisioning",
    ],
    syncStatus: "Synced",
    rawBOM:
      "Looking to purchase high-density dual socket servers.\nNeed 48 servers with Intel Gold 32-core CPUs.\nEach server is required to have 512GB Memory (RDIMM 4800MT/s) and at least 15TB of PCIe NVMe Solid State arrays.\nDual 25G Ethernet NIC connections required for high speed interconnect.",
    solutions: [
      {
        id: "sol-master-u1",
        name: "Master Architectural Solution",
        targetUcidId: crypto.randomUUID(),
        vendorSubmissions: [
          {
            id: "vs-u1-hpe",
            vendor: "HPE",
            label: "HPE ProLiant DL380 Gen11 Alternative",
            totalPrice: 244800,
            originalPrice: 261000,
            savings: 16200,
            complianceScore: 98,
            configs: [
              {
                id: "cfg-u1-hpe-1",
                name: "HPE Server Config",
                totalPrice: 244800,
                originalPrice: 261000,
                savings: 16200,
                items: [
                  {
                    id: "bi-1",
                    partNumber: "P40411-B21",
                    name: "HPE ProLiant DL380 Gen11 8SFF Chassis",
                    type: "Chassis",
                    quantity: 24,
                    unitPrice: 3400,
                  },
                  {
                    id: "bi-2",
                    partNumber: "P40424-B21",
                    name: "Intel Xeon Gold 6430 32-Core 2.1GHz CPU",
                    type: "Processor",
                    quantity: 48,
                    unitPrice: 2150,
                  },
                  {
                    id: "bi-3",
                    partNumber: "P38454-B21",
                    name: "HPE 64GB Dual Rank DDR5-4800 RAM Module",
                    type: "Memory",
                    quantity: 192,
                    unitPrice: 580,
                  },
                  {
                    id: "bi-4",
                    partNumber: "P40483-B21",
                    name: "HPE 3.84TB NVMe SSD",
                    type: "Drive",
                    quantity: 96,
                    unitPrice: 1220,
                  },
                  {
                    id: "bi-5",
                    partNumber: "P40445-B21",
                    name: "HPE Broadcom Dual Port 10/25Gb Ethernet NIC",
                    type: "Network Adapter",
                    quantity: 24,
                    unitPrice: 410,
                  },
                ],
              },
            ],
          },
          {
            id: "vs-u1-dell",
            vendor: "Dell",
            label: "Dell PowerEdge R760 Alternative",
            totalPrice: 239630,
            originalPrice: 255200,
            savings: 15570,
            complianceScore: 96,
            configs: [
              {
                id: "cfg-u1-dell-1",
                name: "Dell Server Config",
                totalPrice: 239630,
                originalPrice: 255200,
                savings: 15570,
                items: [
                  {
                    id: "bi-6",
                    partNumber: "210-BFXS",
                    name: "Dell PowerEdge R760 8SFF Chassis",
                    type: "Chassis",
                    quantity: 24,
                    unitPrice: 3250,
                  },
                  {
                    id: "bi-7",
                    partNumber: "338-CHYT",
                    name: "Intel Xeon Gold 6430 32-Core CPU Equiv",
                    type: "Processor",
                    quantity: 48,
                    unitPrice: 2190,
                  },
                  {
                    id: "bi-8",
                    partNumber: "370-AHFF",
                    name: "Dell 64GB RDIMM 4800MT/s RAM",
                    type: "Memory",
                    quantity: 192,
                    unitPrice: 595,
                  },
                  {
                    id: "bi-9",
                    partNumber: "400-BPSB",
                    name: "Dell 3.84TB NVMe SSD SFF",
                    type: "Drive",
                    quantity: 96,
                    unitPrice: 1195,
                  },
                  {
                    id: "bi-10",
                    partNumber: "540-BCOZ",
                    name: "Broadcom Dual Port 10/25Gb SFP28 Adapter",
                    type: "Network Adapter",
                    quantity: 24,
                    unitPrice: 395,
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
    events: [
      {
        timestamp: "2026-06-01T10:24:12Z",
        level: "info",
        msg: "System Ingested Raw BOQ via Email API Pipeline",
      },
      {
        timestamp: "2026-06-01T10:25:30Z",
        level: "ok",
        msg: "Core constraints extracted: 48x Intel 32-Core, 512GB Memory, 15TB PCIe Storage",
      },
      {
        timestamp: "2026-06-01T10:26:01Z",
        level: "ok",
        msg: "Pre-intelligence catalog matching complete.",
      },
      {
        timestamp: "2026-06-01T10:30:15Z",
        level: "ok",
        msg: "Dual alternatives constructed: HPE DL380 Gen11 vs Dell R760",
      },
      {
        timestamp: "2026-06-01T11:12:44Z",
        level: "warn",
        msg: "API Warning — Dell transaction endpoint returned high queue load",
      },
      {
        timestamp: "2026-06-01T11:13:00Z",
        level: "ok",
        msg: "Vendor provisioning online: Contract pricing synced containing -6% discount",
      },
    ],
    snapshots: [],
  },
  {
    id: "u2",
    displayId: "UCID-2026-0042",
    name: "Object Storage Capacity — Dell Isilon Backup Archive",
    solutionName: "East Backup Storage Consolidation",
    priority: "critical",
    projectRef: "PRJ-STO-BACKUP-EAST",
    createdAt: "2026-06-03 14:15 PM",
    currentStep: "pre-intelligence",
    completedSteps: ["boq-intake"],
    syncStatus: "Out-of-Sync",
    rawBOM:
      "Procure 12x Dell high capacity nodes.\nNeed 3.84TB SSDs (at least 24 units).\nChassis must support large storage controller capabilities.",
    solutions: [
      {
        id: "sol-master-u2",
        name: "Master Architectural Solution",
        targetUcidId: crypto.randomUUID(),
        vendorSubmissions: [
          {
            id: "vs-u2-dell",
            vendor: "Dell",
            label: "Dell Storage Deployment Node Config",
            totalPrice: 65110,
            originalPrice: 74700,
            savings: 9590,
            complianceScore: 92,
            configs: [
              {
                id: "cfg-u2-dell-1",
                name: "Dell Storage Config",
                totalPrice: 65110,
                originalPrice: 74700,
                savings: 9590,
                items: [
                  {
                    id: "bi-11",
                    partNumber: "210-BFXS",
                    name: "Dell PowerEdge R760 8SFF Chassis",
                    type: "Chassis",
                    quantity: 12,
                    unitPrice: 3250,
                  },
                  {
                    id: "bi-12",
                    partNumber: "400-BPSB",
                    name: "Dell 3.84TB Enterprise NVMe SSD",
                    type: "Drive",
                    quantity: 24,
                    unitPrice: 1190,
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
    events: [
      {
        timestamp: "2026-06-03T14:15:32Z",
        level: "info",
        msg: "Ingested raw CSV sheet containing 2 records",
      },
      {
        timestamp: "2026-06-03T14:17:11Z",
        level: "warn",
        msg: "Price mismatch detected on 24x 400-BPSB SSD storage cards. Direct API quotes $1,190 vs BOQ $1,590.",
      },
    ],
    snapshots: [],
  },
];
