import { Solution } from "../types";

export const BOQ_PRESETS: Record<string, { rawText: string; sols: Solution[] }> = {
  "hpe-legacy": {
    rawText: `[AUTOMATED WORKBOOK INGESTION - HPE LOGGED QUOTE]\nFile: HPE_PARTNER_QUOTE_6130_EOL.xlsx\nTarget Chassis: DL380 Gen11 NC SFF (P40411-B21) x10 Units\nProcessed CPU SKU: 815100-B21 (Intel Xeon Gold 6130 Legacy CPU) x20 Units\nMemory DIMM RAM: P38454-B21 (64GB DDR5) x80 Units\n\nNotes: Lead duration set to 45 Days due to obsolete processor SKU.`,
    sols: [
      {
        id: `sol-manual-hpe-fixed`,
        name: "HPE Alternative (Ingested: HPE_PARTNER_QUOTE_6130_EOL.xlsx)",
        targetUcidId: "unknown",
        vendorSubmissions: [
          {
            id: `vs-manual-hpe-fixed`,
            vendor: "HPE",
            label: "HPE Alternative (Ingested: HPE_PARTNER_QUOTE_6130_EOL.xlsx)",
            totalPrice: 118200,
            originalPrice: 125000,
            savings: 6800,
            complianceScore: 78,
            configs: [
              {
                id: "cfg-1",
                name: "Auto-Config",
                totalPrice: 118200,
                originalPrice: 125000,
                savings: 6800,
                items: [
                  {
                    id: "item-mi-1",
                    partNumber: "P40411-B21",
                    name: "HPE ProLiant DL380 Gen11 CTO Chassis",
                    type: "Chassis",
                    quantity: 10,
                    unitPrice: 3400,
                  },
                  {
                    id: "item-mi-2",
                    partNumber: "815100-B21",
                    name: "Intel Xeon Gold 6130 Processor [EOL Sourcing Risk]",
                    type: "Processor",
                    quantity: 20,
                    unitPrice: 1890,
                  },
                  {
                    id: "item-mi-3",
                    partNumber: "P38454-B21",
                    name: "HPE 64GB DDR5 memory module RDIMM",
                    type: "Memory",
                    quantity: 80,
                    unitPrice: 580,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: `sol-manual-dell-fixed`,
        name: "Dell Alternative (Autogenerated Peer Modern Equivalent)",
        targetUcidId: "unknown",
        vendorSubmissions: [
          {
            id: `vs-manual-dell-fixed`,
            vendor: "Dell",
            label: "Dell Alternative (Autogenerated Peer Modern Equivalent)",
            totalPrice: 120100,
            originalPrice: 125200,
            savings: 5100,
            complianceScore: 98,
            configs: [
              {
                id: "cfg-2",
                name: "Auto-Config",
                totalPrice: 120100,
                originalPrice: 125200,
                savings: 5100,
                items: [
                  {
                    id: "item-mi-d1",
                    partNumber: "210-BFXS",
                    name: "Dell PowerEdge R760 8SFF Chassis",
                    type: "Chassis",
                    quantity: 10,
                    unitPrice: 3250,
                  },
                  {
                    id: "item-mi-d2",
                    partNumber: "338-CHYT",
                    name: "Intel Xeon Gold 6430 32-Core CPU",
                    type: "Processor",
                    quantity: 20,
                    unitPrice: 2190,
                  },
                  {
                    id: "item-mi-d3",
                    partNumber: "370-AHFF",
                    name: "Dell 64GB RDIMM 4800MT/s RAM",
                    type: "Memory",
                    quantity: 40,
                    unitPrice: 595,
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  "dell-overcharge": {
    rawText: `[AUTOMATED WORKBOOK INGESTION - DELL PREMIER PORTAL]\nFile: DELL_PREMIER_QUOTE_DRAFT.csv\nTarget Chassis: Dell PowerEdge R760 8SFF (210-BFXS) x12 Units\nStorage Drive SKU: 400-BPSB (Dell 3.84TB SAS Read Intensive SSD SFF) x24 Units [Mark-up: quote price is $1,590 vs contract $1,190]\nMemory: 370-AHFF (64GB RDIMM DDR5) x48 Units`,
    sols: [
      {
        id: `sol-manual-dell-fixed2`,
        name: "Dell Alternative (Ingested: DELL_PREMIER_QUOTE_DRAFT.csv)",
        targetUcidId: "unknown",
        vendorSubmissions: [
          {
            id: `vs-manual-dell-fixed2`,
            vendor: "Dell",
            label: "Dell Alternative (Ingested: DELL_PREMIER_QUOTE_DRAFT.csv)",
            totalPrice: 105720,
            originalPrice: 115000,
            savings: 9280,
            complianceScore: 85,
            configs: [
              {
                id: "cfg-de-1",
                name: "Auto-Config",
                totalPrice: 105720,
                originalPrice: 115000,
                savings: 9280,
                items: [
                  {
                    id: "item-mi-de1",
                    partNumber: "210-BFXS",
                    name: "Dell PowerEdge R760 8SFF Chassis Base Unit",
                    type: "Chassis",
                    quantity: 12,
                    unitPrice: 3250,
                  },
                  {
                    id: "item-mi-de2",
                    partNumber: "400-BPSB",
                    name: "Dell 3.84TB SAS Read Intensive SSD SFF [Markup Variance]",
                    type: "Drive",
                    quantity: 24,
                    unitPrice: 1590,
                  },
                  {
                    id: "item-mi-de3",
                    partNumber: "370-AHFF",
                    name: "Dell 64GB RDIMM 4800MT/s memory module",
                    type: "Memory",
                    quantity: 48,
                    unitPrice: 595,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: `sol-manual-hpe-fixed2`,
        name: "HPE Alternative (Autogenerated Peer Base)",
        targetUcidId: "unknown",
        vendorSubmissions: [
          {
            id: `vs-manual-hpe-fixed2`,
            vendor: "HPE",
            label: "HPE Alternative (Autogenerated Peer Base)",
            totalPrice: 98160,
            originalPrice: 110000,
            savings: 11840,
            complianceScore: 98,
            configs: [
              {
                id: "cfg-hpe-1",
                name: "Auto-Config",
                totalPrice: 98160,
                originalPrice: 110000,
                savings: 11840,
                items: [
                  {
                    id: "item-mi-h1",
                    partNumber: "P40411-B21",
                    name: "HPE ProLiant DL380 Gen11 8SFF Chassis",
                    type: "Chassis",
                    quantity: 12,
                    unitPrice: 3400,
                  },
                  {
                    id: "item-mi-h2",
                    partNumber: "P40483-B21",
                    name: "HPE 3.84TB NVMe SSD Sourced",
                    type: "Drive",
                    quantity: 24,
                    unitPrice: 1220,
                  },
                  {
                    id: "item-mi-h3",
                    partNumber: "P38454-B21",
                    name: "HPE 64GB Dual Rank DDR5 module",
                    type: "Memory",
                    quantity: 48,
                    unitPrice: 580,
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  "cisco-asymmetry": {
    rawText: `[AUTOMATED WORKBOOK INGESTION - CISCO MATRIX CHALLENGE]\nFile: CISCO_UCS_AS_SYMMETRICAL.csv\nTarget Chassis: UCS C240 M7 Rack Server (UCSC-C240-M7S) x12 Units\nProcessor Unit: UCS-CPU-I6430 x24 Units\nMemory Allocation: UCS-MR-64G2ED-E (Cisco 64GB DDR5 RDIMM) x5 modules/node [Total Qty: 60 units]`,
    sols: [
      {
        id: `sol-manual-cisco-fixed`,
        name: "Cisco Alternative (Ingested: CISCO_UCS_AS_SYMMETRICAL.csv)",
        targetUcidId: "unknown",
        vendorSubmissions: [
          {
            id: `vs-manual-cisco-fixed`,
            vendor: "Cisco",
            label: "Cisco Alternative (Ingested: CISCO_UCS_AS_SYMMETRICAL.csv)",
            totalPrice: 140520,
            originalPrice: 148000,
            savings: 7480,
            complianceScore: 82,
            configs: [
              {
                id: "cfg-c1",
                name: "Auto-Config",
                totalPrice: 140520,
                originalPrice: 148000,
                savings: 7480,
                items: [
                  {
                    id: "item-mi-c1",
                    partNumber: "UCSC-C240-M7S",
                    name: "Cisco UCS C240 M7 Rack Server Chassis",
                    type: "Chassis",
                    quantity: 12,
                    unitPrice: 4100,
                  },
                  {
                    id: "item-mi-c2",
                    partNumber: "UCS-CPU-I6430",
                    name: "UCS Intel Xeon Gold 6430 32-Core CPU",
                    type: "Processor",
                    quantity: 24,
                    unitPrice: 2280,
                  },
                  {
                    id: "item-mi-c3",
                    partNumber: "UCS-MR-64G2ED-E",
                    name: "UCS 64GB DDR5 memory module [Asymmetric Layout]",
                    type: "Memory",
                    quantity: 60,
                    unitPrice: 610,
                  },
                ],
              },
            ],
          },
        ],
      },
      {
        id: `sol-manual-dell-fixed3`,
        name: "Dell Alternative (Autogenerated Peer Base)",
        targetUcidId: "unknown",
        vendorSubmissions: [
          {
            id: `vs-manual-dell-fixed3`,
            vendor: "Dell",
            label: "Dell Alternative (Autogenerated Peer Base)",
            totalPrice: 138000,
            originalPrice: 145000,
            savings: 7000,
            complianceScore: 98,
            configs: [
              {
                id: "cfg-cd1",
                name: "Auto-Config",
                totalPrice: 138000,
                originalPrice: 145000,
                savings: 7000,
                items: [
                  {
                    id: "item-mi-cd1",
                    partNumber: "210-BFXS",
                    name: "Dell PowerEdge R760 8SFF Chassis",
                    type: "Chassis",
                    quantity: 12,
                    unitPrice: 3250,
                  },
                  {
                    id: "item-mi-cd2",
                    partNumber: "338-CHYT",
                    name: "Intel Xeon Gold 6430 32-Core CPU",
                    type: "Processor",
                    quantity: 24,
                    unitPrice: 2190,
                  },
                  {
                    id: "item-mi-cd3",
                    partNumber: "370-AHFF",
                    name: "Dell 64GB RDIMM 4800MT/s RAM",
                    type: "Memory",
                    quantity: 96,
                    unitPrice: 595,
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  "divergence-split": {
    rawText: `[AUTOMATED WORKBOOK INGESTION]\nFile: YLNG_22_Server_Config.xlsx\nTarget Chassis: DL380 Gen12 (P6730-B21) x22 Units\n\nNotes: 22 Servers base config. We need to split this into 5 servers (with transceivers) and 17 servers (without) during cleansing.`,
    sols: [
      {
        id: `sol-divergence-base`,
        name: "Base 22 Server Config (Unsplit)",
        targetUcidId: "unknown",
        vendorSubmissions: [
          {
            id: `vs-divergence-base`,
            vendor: "HPE",
            label: "HPE Config",
            totalPrice: 220000,
            originalPrice: 240000,
            savings: 20000,
            complianceScore: 100,
            configs: [
              {
                id: "cfg-base-22",
                name: "Base Server Config (Qty 22)",
                totalPrice: 220000,
                originalPrice: 240000,
                savings: 20000,
                items: [
                  {
                    id: "item-base-1",
                    partNumber: "P6730-B21",
                    name: "HPE ProLiant DL380 Gen12 Chassis",
                    type: "Chassis",
                    quantity: 22,
                    unitPrice: 5000,
                  },
                  {
                    id: "item-base-2",
                    partNumber: "P49610-B21",
                    name: "HPE 64GB DDR5 Memory",
                    type: "Memory",
                    quantity: 176, // 8 per server
                    unitPrice: 500,
                  }
                ],
              }
            ],
          }
        ]
      }
    ]
  }
};
